@imaa.API_HostAddress = https://localhost:44341

GET {{imaa.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{imaa.API_HostAddress}}/processdata
###

GET {{imaa.API_HostAddress}}/TestBadRequestException

###

GET {{imaa.API_HostAddress}}/TestUnauthorizedException

###
