import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { ListViewTableHeader } from '../models/listview-model';

@Injectable({
  providedIn: 'root',
})
export class InvestmentsService {
  private viewListData: ListViewTableHeader[] = [
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
    {
      requestName: 'User Input',
      opEntity: 'User Input',
      adminDivision: 'User Input',
      businessArea: 'User Input',
      approvingDiv: 'User Input',
      endorsingDiv: 'User Input',
      requester: 'User Input',
    },
  ];
  constructor() {}

  public getViewListData(): Observable<ListViewTableHeader[]> {
    return of(this.viewListData);
  }
}
