import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { ListViewTableHeader } from '../models/listview-model';

@Injectable({
  providedIn: 'root',
})
export class InvestmentsService {
  private viewListData: ListViewTableHeader[] = [
    {
      requestName: 'Request Name 01',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Approved',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'EUR',
    },
    {
      requestName: 'Request Name 02',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Evaluation Pending',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'EUR',
    },
    {
      requestName: 'Request Name 03',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Rejected',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'USD',
    },
    {
      requestName: 'Request Name 04',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Approved',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'EUR',
    },
    {
      requestName: 'Request Name 05',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Under Review',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'SEK',
    },
    {
      requestName: 'Request Name 06',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'In Preparation',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'SEL',
    },
    {
      requestName: 'Request Name 07',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Approved',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'EUR',
    },
    {
      requestName: 'Request Name 08',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Under Review',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'USD',
    },
    {
      requestName: 'Request Name 09',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Proposed',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'SEK',
    },
    {
      requestName: 'Request Name 10',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Approved',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'EUR',
    },
    {
      requestName: 'Request Name 11',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Rejected',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'SEL',
    },
    {
      requestName: 'Request Name 12',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Approved',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'USD',
    },
    {
      requestName: 'Request Name 13',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Approved',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'USD',
    },
    {
      requestName: 'Request Name 14',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Proposed',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'SEK',
    },
    {
      requestName: 'Request Name 15',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Proposed',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'SEL',
    },
    {
      requestName: 'Request Name 16',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Evaluation Pending',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'EUR',
    },
    {
      requestName: 'Request Name 17',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Revision Needed',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'EUR',
    },
    {
      requestName: 'Request Name 18',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Revision Needed',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'SEK',
    },
    {
      requestName: 'Request Name 19',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Approved',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'USD',
    },
    {
      requestName: 'Request Name 20',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Approved',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'USD',
    },
    {
      requestName: 'Request Name 21',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Proposed',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'SEL',
    },
    {
      requestName: 'Request Name 22',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Proposed',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'SEL',
    },
    {
      requestName: 'Request Name 23',
      opEntity: 'Info',
      approvingDiv: 'Info',
      businessArea: 'Info',
      approvingStatus: 'Approved',
      finalAppDate: 'mm/dd/yyyy',
      curency: 'EUR',
    },
  ];
  constructor() {}

  public getViewListData(): Observable<ListViewTableHeader[]> {
    return of(this.viewListData);
  }
}
