import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { ListViewTableHeader } from '../models/listview-model';

@Injectable({
  providedIn: 'root',
})
export class InvestmentsService {
  private viewListData: ListViewTableHeader[] = [
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
    {
      RequestName: 'User Input',
      OpEntity: 'User Input',
      AdminDivision: 'User Input',
      BusinessArea: 'User Input',
      ApprovingDiv: 'User Input',
      EndorsingDiv: 'User Input',
      Requester: 'User Input',
    },
  ];
  constructor() {}

  getViewListData(): Observable<any> {
    return of(this.viewListData);
  }
}
